export const medications = [
  {
    generic_name: "Ipratropium",
    brand_name: "Atrovent",
    delivery_type: "pMDI",
    class: "Anticholinergic - Short-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.073,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Aclidinium",
    brand_name: "Eklira Genuait",
    delivery_type: "DPI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.009,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Airomir MDI",
    delivery_type: "pMDI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.0486,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Airomir Autohaler",
    delivery_type: "pMDI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.0486,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Salamol MDI",
    delivery_type: "pMDI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.06,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Dalamol Easi-Breathe",
    delivery_type: "pMDI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.06,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Ventolin Accuhaler",
    delivery_type: "DPI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.01,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Salbutamol",
    brand_name: "Ventolin Evohaler",
    delivery_type: "pMDI",
    class: "Anticholinergic - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.141,
    carbon_footprint_rating: 3,
  },
  {
    generic_name: "Formoterol",
    brand_name: "Atimos Modulite",
    delivery_type: "pMDI",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.13,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Formoterol",
    brand_name: "Easyhaler Formoterol",
    delivery_type: "DPI",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: -0.005,
    carbon_footprint_rating: 0,
  },
  {
    generic_name: "Formoterol",
    brand_name: "Foradil",
    delivery_type: "DPI + separate caps",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.019,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Indacaterol",
    brand_name: "Onbrez Breezhaler",
    delivery_type: "DPI + separate caps",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.019,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Salmeterol",
    brand_name: "Neovent",
    delivery_type: "pMDI",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.13,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salmeterol",
    brand_name: "Serevent Accuhaler",
    delivery_type: "DPI",
    class: "Beta 2 Agonist - Long-Acting",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.012,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Beclometasone",
    brand_name: "Easyhaler Belcometasone",
    delivery_type: "DPI",
    class: "Anti-Inflammatories",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: -0.003,
    carbon_footprint_rating: 0,
  },
  {
    generic_name: "Beclometasone",
    brand_name: "Kelhale",
    delivery_type: "pMDI",
    class: "Anti-Inflammatories",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.087,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Beclometasone",
    brand_name: "Qvar MDI",
    delivery_type: "pMDI",
    class: "Anti-Inflammatories",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.102,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Beclometasone",
    brand_name: "Qvar Autohaler",
    delivery_type: "pMDI",
    class: "Anti-Inflammatories",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.102,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Beclometasone",
    brand_name: "Qvar Easi-Breathe",
    delivery_type: "pMDI",
    class: "Anti-Inflammatories",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.102,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Formoterol/aclidinium",
    brand_name: "Duaklir Genuair",
    delivery_type: "DPI",
    class: "Combination Preparation",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.009,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Formoterol/beclometasone/glycopyrronium",
    brand_name: "Trimbow pMDI",
    delivery_type: "pMDI",
    class: "Combination Preparation",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.118,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Formoterol/beclometasone/glycopyrronium",
    brand_name: "Trimbow NEXThaler",
    delivery_type: "DPI",
    class: "Combination Preparation",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.007,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Salmeterol/fluticasone",
    brand_name: "AirFluSal MDI",
    delivery_type: "pMDI",
    class: "Combination Preparation",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.161,
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Salmeterol/fluticasone",
    brand_name: "AirFluSal Forspiro",
    delivery_type: "DPI",
    class: "Combination Preparation",
    unit_dose: "1 puff",
    carbon_emission_per_unit_dose: 0.01,
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "Amoxicillin",
    brand_name: "Amoxil",
    delivery_type: "Injection",
    class: "Penicillin",
    unit_dose: "50 mg",
    carbon_emission_per_unit_dose: "NA",
    carbon_footprint_rating: 2,
  },
  {
    generic_name: "Doxycycline",
    brand_name: "Doryx",
    delivery_type: "Injection",
    class: "Tetracycline",
    unit_dose: "100 mg",
    carbon_emission_per_unit_dose: "NA",
    carbon_footprint_rating: 3,
  },
  {
    generic_name: "cephalexin",
    brand_name: "Keflex",
    delivery_type: "Injection",
    class: "Cephalosporin",
    unit_dose: "50 mg",
    carbon_emission_per_unit_dose: "NA",
    carbon_footprint_rating: 1,
  },
  {
    generic_name: "ciprofloxacin",
    brand_name: "Cipro",
    delivery_type: "Injection",
    class: "Quinolone",
    unit_dose: "50 mg",
    carbon_emission_per_unit_dose: "NA",
    carbon_footprint_rating: 1,
  },
];
